---

- name: "Including distro-specific variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"

- name: "Setting things up for {{ ansible_distribution }}"
  include: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu', 'Gentoo', 'Debian', 'Fedora' ]
  tags: [ 'install' ]

- name: "Making sure a default self-signed cert is present"
  command: openssl req -newkey rsa:4096 -x509 -nodes -days 3650 -sha512 -subj "/C=US/L=LA/O=VAIZ/OU=IT/CN={{ ansible_fqdn }}" -keyout /etc/ssl/private/mage-snakeoil.key -out /etc/ssl/certs/mage-snakeoil.pem
  args:
    creates: "/etc/ssl/certs/mage-snakeoil.pem"
  tags: [ 'configure' ]

- name: "Making sure dhparam file is present"
  command: openssl dhparam -out /etc/ssl/private/dhparams.pem "{{ dhparam_size }}" creates=/etc/ssl/private/dhparams.pem
  tags: [ 'configure' ]
  
- name: "Ensure locale en_US.UTF-8 locale is present"
  locale_gen:
    name: en_US.UTF-8
    state: present
  tags: [ 'configure' ]
