---
- name: "Installing packages"
  portage: 
    package: "{{ item }}"
    update: yes
    deep: yes
    sync: web
    newuse: yes
  with_items:
    - "{{ mage_packages }}"
    
- name: "Initializing eix"
  command: eix-update
  args:
    creates: /var/cache/eix/portage.eix